name: Generate Midjourney Prompts

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:      # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    
    # Ensure only one workflow runs at a time
    concurrency:
      group: generate-prompts
      cancel-in-progress: false
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Verify environment variables
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "Error: OPENAI_API_KEY is not set"
            exit 1
          fi
          if [ -z "$ASSISTANT_ID" ]; then
            echo "Error: ASSISTANT_ID is not set"
            exit 1
          fi
          echo "Environment variables are properly set"
          # Verify API key format (should start with 'sk-')
          if [[ ! "$OPENAI_API_KEY" =~ ^sk- ]]; then
            echo "Error: OPENAI_API_KEY format is incorrect. Should start with 'sk-'"
            exit 1
          fi
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}

      - name: Generate prompts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
        run: |
          echo "Starting prompt generation..."
          python generate_prompts.py -n 5  # Generate 50 prompts per hour
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      
      - name: Commit and push if changed
        run: |
          if [[ -f midjourney_prompts_*.txt ]]; then
            git add midjourney_prompts_*.txt
            timestamp=$(date -u)
            git commit -m "Auto-generate prompts: ${timestamp}" || exit 0
            git push
          fi
