name: Generate Midjourney Prompts

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: write        # Required for pushing changes

env:
  SENDER_EMAIL: "github-actions[bot]@users.noreply.github.com"

jobs:
  generate:
    runs-on: ubuntu-latest
    
    # Ensure only one workflow runs at a time
    concurrency:
      group: generate-prompts
      cancel-in-progress: false
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the automatic GITHUB_TOKEN
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Verify environment variables
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "Error: OPENAI_API_KEY is not set"
            exit 1
          fi
          if [ -z "$ASSISTANT_ID" ]; then
            echo "Error: ASSISTANT_ID is not set"
            exit 1
          fi
          echo "Environment variables are properly set"
          # Verify API key format (should start with 'sk-')
          if [[ ! "$OPENAI_API_KEY" =~ ^sk- ]]; then
            echo "Error: OPENAI_API_KEY format is incorrect. Should start with 'sk-'"
            exit 1
          fi
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}

      - name: Generate prompts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
        run: |
          echo "Starting prompt generation..."
          python generate_prompts.py -n 50  # Generate 50 prompts per hour
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      
      - name: Commit and push if changed
        id: commit
        run: |
          if [[ -f midjourney_prompts_*.txt ]]; then
            # Find the modified file
            modified_file=$(git status --porcelain | grep "midjourney_prompts_" | awk '{print $2}')
            if [ -n "$modified_file" ]; then
              git add "$modified_file"
              timestamp=$(date -u)
              git commit -m "Auto-generate prompts: ${timestamp}"
              git push
              echo "Successfully pushed changes"
              echo "UPDATED_FILE=$modified_file" >> $GITHUB_ENV
              echo "CHANGES_MADE=true" >> $GITHUB_ENV
            else
              echo "No changes to commit"
              echo "CHANGES_MADE=false" >> $GITHUB_ENV
            fi
          else
            echo "No prompt files found"
            echo "CHANGES_MADE=false" >> $GITHUB_ENV
          fi

      - name: Send email
        if: success() && env.CHANGES_MADE == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: New Midjourney Prompts Generated
          from: ${{ env.SENDER_EMAIL }}
          to: ${{ secrets.EMAIL_TO }}
          body: |
            New Midjourney prompts have been generated.
            
            Generated at: ${{ github.event.repository.updated_at }}
            Repository: ${{ github.repository }}
            Filename: ${{ env.UPDATED_FILE }}
            
            The updated prompts file is attached.
          attachments: ${{ env.UPDATED_FILE }}
